apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: slack-app-hpa
  namespace: bot-infra
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: slack-app
  minReplicas: 1
  maxReplicas: 1  # Keep at 1 for Slack socket mode
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
